name: My Workflow

on:
  push:
    branches:
      - main


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use the secret
        env:
          ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: echo $ACCESS_TOKEN
